//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperationManager.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class AFAmazonS3RequestSerializer<AFURLRequestSerialization>, NSURL;

@interface AFAmazonS3Manager : AFHTTPRequestOperationManager <NSSecureCoding, NSCopying>
{
    NSURL *_s3_baseURL;
}

+ (id)keyPathsForValuesAffectingBaseURL;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_s3_baseURL;

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)deleteObjectWithPath:(id)arg1 success:(id)arg2 failure:(id)arg3;
- (id)setObjectWithMethod:(id)arg1 file:(id)arg2 destinationPath:(id)arg3 parameters:(id)arg4 progress:(id)arg5 success:(id)arg6 failure:(id)arg7;
- (id)putObjectWithFile:(id)arg1 destinationPath:(id)arg2 parameters:(id)arg3 progress:(id)arg4 success:(id)arg5 failure:(id)arg6;
- (id)postObjectWithFile:(id)arg1 destinationPath:(id)arg2 parameters:(id)arg3 progress:(id)arg4 success:(id)arg5 failure:(id)arg6;
- (id)getObjectWithPath:(id)arg1 outputStream:(id)arg2 progress:(id)arg3 success:(id)arg4 failure:(id)arg5;
- (id)getObjectWithPath:(id)arg1 progress:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (id)headObjectWithPath:(id)arg1 success:(id)arg2 failure:(id)arg3;
- (id)deleteBucket:(id)arg1 success:(id)arg2 failure:(id)arg3;
- (id)putBucket:(id)arg1 parameters:(id)arg2 success:(id)arg3 failure:(id)arg4;
- (id)getBucket:(id)arg1 success:(id)arg2 failure:(id)arg3;
- (id)getServiceWithSuccess:(id)arg1 failure:(id)arg2;
- (id)enqueueS3RequestOperationWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3 success:(id)arg4 failure:(id)arg5;
- (id)initWithAccessKeyID:(id)arg1 secret:(id)arg2;
- (id)initWithBaseURL:(id)arg1;

// Remaining properties
@property(retain, nonatomic) AFAmazonS3RequestSerializer<AFURLRequestSerialization> *requestSerializer; // @dynamic requestSerializer;

@end

