//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class BCLicense, NSDate, NSString, NSURL, NSURLSession;

@interface BCLicenseManager : NSObject
{
    BOOL _completedLoadingLicense;
    BCLicense *_license;
    NSString *_applicationID;
    NSString *_publicCertificate;
    NSURL *_licenseURL;
    NSURLSession *_urlSession;
    NSDate *_applicationBuildDate;
}

@property(retain, nonatomic) NSDate *applicationBuildDate; // @synthesize applicationBuildDate=_applicationBuildDate;
@property(nonatomic) BOOL completedLoadingLicense; // @synthesize completedLoadingLicense=_completedLoadingLicense;
@property(retain, nonatomic) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
@property(retain, nonatomic) NSURL *licenseURL; // @synthesize licenseURL=_licenseURL;
@property(retain, nonatomic) NSString *publicCertificate; // @synthesize publicCertificate=_publicCertificate;
@property(retain, nonatomic) NSString *applicationID; // @synthesize applicationID=_applicationID;
@property(retain, nonatomic) BCLicense *license; // @synthesize license=_license;

- (id)apiURLForMethod:(id)arg1 queryItems:(id)arg2;
- (id)apiURL;
- (id)websiteAvailableVersionsURL;
- (id)websiteRenewalURL;
- (id)currentVersion;
- (void)processURL:(id)arg1 handler:(id)arg2;
- (void)performUnregisterCall:(id)arg1;
- (void)unregister;
- (void)unregisterWithPrompt;
- (void)licenseStateChanged;
- (void)completeUpdateWithHandler:(id)arg1 status:(long long)arg2 info:(id)arg3 error:(id)arg4;
- (void)checkForDeploymentKeyWithPath:(id)arg1 removeFile:(BOOL)arg2 completionHandler:(id)arg3;
- (void)requestTrialLicenseWithHandler:(id)arg1;
- (void)fallbackToTrial:(id)arg1 completionHandler:(id)arg2;
- (void)processLicenseRefreshResult:(id)arg1 error:(id)arg2 completionHandler:(id)arg3;
- (void)tryToRefreshLicense:(id)arg1 completionHandler:(id)arg2;
- (void)processDataOfRegistration:(id)arg1 handler:(id)arg2;
- (void)registerWithLicenseKey:(id)arg1 handler:(id)arg2;
- (long long)numberOfDaysLeftInTrialMode;
- (BOOL)canRenewLicense;
- (BOOL)canInstallUpdates;
- (id)updateExpirationDate;
- (id)registeredEmailAddress;
- (long long)currentLicenseType;
- (BOOL)licenseVersionIsSupported:(id)arg1;
- (void)validateLicenseWithCompletionHandler:(id)arg1;
- (void)refreshLicenseWithCompletionHandler:(id)arg1;
- (void)updateLicenseWithCompletionHandler:(id)arg1;
- (id)initWithApplicationID:(id)arg1 publicCertificate:(id)arg2 licenseURL:(id)arg3 applicationBuildDate:(id)arg4;

@end

