//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

#import "NSDiscardableContent.h"

@class NSHashTable;

@interface BCObjectPool : NSObject <NSDiscardableContent>
{
    NSHashTable *_pool;
    unsigned long long _maximumPoolCount;
    id _creatorBlock;
}

@property(readonly, copy, nonatomic) id creatorBlock; // @synthesize creatorBlock=_creatorBlock;

- (BOOL)isContentDiscarded;
- (void)discardContentIfPossible;
- (void)endContentAccess;
- (BOOL)beginContentAccess;
@property unsigned long long maximumPoolCount;
- (void)recycleObject:(id)arg1;
- (id)vendObject;
- (id)initWithObjectCreatorBlock:(id)arg1;

@end

