//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSString;

@interface MSAttributeConverter : NSObject
{
    NSString *_attributeName;
    id _conversionBlock;
}

+ (id)converterWithAttributeName:(id)arg1 block:(id)arg2;
@property(readonly, copy, nonatomic) id conversionBlock; // @synthesize conversionBlock=_conversionBlock;
@property(readonly, copy, nonatomic) NSString *attributeName; // @synthesize attributeName=_attributeName;

- (id)convertAttributes:(id)arg1;
- (id)initWithAttributeName:(id)arg1 block:(id)arg2;

@end

