//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class MSDocument;

@interface MSDebugStressTestRendering : NSObject
{
    MSDocument *_document;
}

+ (void)stressTestDocument:(id)arg1;
@property(retain, nonatomic) MSDocument *document; // @synthesize document=_document;

- (id)findRandomParent;
- (id)findRandomLayer;
- (void)runInBackground;
- (void)run;

@end

