//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@import AppKit;

@class NSURL;

@interface MSFolderMonitor : NSObject
{
    struct __FSEventStream *_eventStream;
    NSURL *_folderURL;
    id _contentsChangedBlock;
}

@property(copy, nonatomic) id contentsChangedBlock; // @synthesize contentsChangedBlock=_contentsChangedBlock;
@property(copy, nonatomic) NSURL *folderURL; // @synthesize folderURL=_folderURL;

- (void)dealloc;
- (id)initWithURL:(id)arg1 latency:(double)arg2 contentsChangedBlock:(id)arg3;
- (id)initWithURL:(id)arg1 contentsChangedBlock:(id)arg2;

@end

