//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CHSheetController.h"

@class NSTextField;

@interface MSSaveAsTemplateSheet : CHSheetController
{
    id _inputCompletionBlock;
    NSTextField *_inputField;
}

+ (id)runForDocument:(id)arg1 completionBlock:(id)arg2;
@property(retain, nonatomic) NSTextField *inputField; // @synthesize inputField=_inputField;
@property(copy, nonatomic) id inputCompletionBlock; // @synthesize inputCompletionBlock=_inputCompletionBlock;

- (void)confirm:(id)arg1;

@end

