//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSSortableObjectMenuBuilder.h"

@class NSImage;

@interface MSSymbolsMenuBuilder : MSSortableObjectMenuBuilder
{
    NSImage *_initialImage;
}

@property(retain, nonatomic) NSImage *initialImage; // @synthesize initialImage=_initialImage;

- (void)prepareForDisplay:(id)arg1;
- (id)init;

@end

