//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (NSArray_Blocks)
+ (id)arrayWithCapacity:(unsigned long long)arg1 fill:(id)arg2;
- (BOOL)containsObjectPassingTest:(id)arg1;
- (unsigned long long)indexOfFirstObjectPassingTest:(id)arg1;
- (id)firstObjectPassingTest:(id)arg1;
- (double)sum:(id)arg1;
@end

