//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSet.h"

@interface NSSet (NSSet_SmallBlocks)
- (BOOL)containsObjectPassingTest:(id)arg1;
- (id)map:(id)arg1;
- (void)each:(id)arg1;
@end

